"""baseline

Revision ID: 2818ae96ff36
Revises: 
Create Date: 2026-08-16 13:50:19.945966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2818ae96ff36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('site_currency_code', sa.String(), nullable=True),
    sa.Column('site_fx_rate_to_usd', sa.Float(), nullable=True),
    sa.Column('inhouse_labor_currency_code', sa.String(), nullable=True),
    sa.Column('inhouse_fx_rate_to_usd', sa.Float(), nullable=True),
    sa.Column('local_labor_currency_code', sa.String(), nullable=True),
    sa.Column('local_fx_rate_to_usd', sa.Float(), nullable=True),
    sa.Column('material_currency_code', sa.String(), nullable=True),
    sa.Column('material_fx_rate_to_usd', sa.Float(), nullable=True),
    sa.Column('working_days_per_month', sa.Float(), nullable=True),
    sa.Column('wages_oh_rate_pct', sa.Float(), nullable=True),
    sa.Column('food_per_month_local', sa.Float(), nullable=True),
    sa.Column('accommodation_per_month_local', sa.Float(), nullable=True),
    sa.Column('local_travel_per_month_local', sa.Float(), nullable=True),
    sa.Column('air_ticket_per_year_local', sa.Float(), nullable=True),
    sa.Column('visa_per_year_local', sa.Float(), nullable=True),
    sa.Column('other_allowance_per_day_usd', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('support_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('default_code', sa.String(), nullable=True),
    sa.Column('uom', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wetworks_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('uom', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('default_code', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('needs_setup', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('support_item_id', sa.Integer(), nullable=False),
    sa.Column('qty_per_unit', sa.Float(), nullable=False),
    sa.Column('wastage_pct', sa.Float(), nullable=False),
    sa.Column('markup_pct', sa.Float(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['wetworks_products.id'], ),
    sa.ForeignKeyConstraint(['support_item_id'], ['support_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('country_material_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('support_item_id', sa.Integer(), nullable=False),
    sa.Column('unit_price_local', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['support_item_id'], ['support_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'support_item_id', name='uq_country_support_item')
    )
    op.create_table('coverage_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('primary_coverage_per_day', sa.Float(), nullable=False),
    sa.Column('secondary_coverage_per_day', sa.Float(), nullable=True),
    sa.Column('inhouse_count', sa.Integer(), nullable=False),
    sa.Column('local_count', sa.Integer(), nullable=False),
    sa.Column('inhouse_salary_month_local', sa.Float(), nullable=False),
    sa.Column('local_salary_month_local', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['wetworks_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('estimator_name', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('default_margin_pct', sa.Float(), nullable=False),
    sa.Column('display_currency', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estimate_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('margin_pct_override', sa.Float(), nullable=True),
    sa.Column('drawing_no', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('material_cost_per_unit', sa.Float(), nullable=True),
    sa.Column('labor_cost_per_unit', sa.Float(), nullable=True),
    sa.Column('wages_cost_per_unit', sa.Float(), nullable=True),
    sa.Column('labor_expenses_per_unit', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['project_locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['wetworks_products.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estimate_line_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimate_line_id', sa.Integer(), nullable=False),
    sa.Column('support_item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['estimate_line_id'], ['estimate_lines.id'], ),
    sa.ForeignKeyConstraint(['support_item_id'], ['support_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estimate_line_components')
    op.drop_table('estimate_lines')
    op.drop_table('project_locations')
    op.drop_table('projects')
    op.drop_table('coverage_rates')
    op.drop_table('country_material_prices')
    op.drop_table('bom_lines')
    op.drop_table('wetworks_products')
    op.drop_table('support_items')
    op.drop_table('countries')
    # ### end Alembic commands ###
