"""add users and project ownership

Revision ID: d6df830062bb
Revises: 2818ae96ff36
Create Date: 2026-08-16 13:50:58.951901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6df830062bb'
down_revision: Union[str, None] = '2818ae96ff36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # batch_alter_table so this also works on SQLite (which can't ALTER
    # constraints directly -- batch mode does a copy-and-move instead). This
    # is a transparent no-op wrapper on Postgres.
    with op.batch_alter_table('projects') as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_projects_owner_id_users', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects') as batch_op:
        batch_op.drop_constraint('fk_projects_owner_id_users', type_='foreignkey')
        batch_op.drop_column('owner_id')
    op.drop_table('users')
    # ### end Alembic commands ###
